### ISSUE TITLE
Split GraphQL server and ingestor into separate processes

### ISSUE THREAD

**Issue by nebolsin** [astroband/astrograph#115]
Currently we a single process running both GraphQL server and ingesting ledgers. It's not very flexible and makes horizontal scaling complicated. 

Let's split the GraphQL server and Ingestor into separate processes, so that we have more fine-grained control over deployment (ex. have 4 GraphQL server instances + 1 ingestor)

**Comment by charlie-wasp** [comment]
I believe, if we want to split the app, we should use some other PubSub implementation for our subscriptions. From the `graphql-subscriptions` [docs](https://github.com/apollographql/graphql-subscriptions#getting-started-with-your-first-subscription):

> Note that the default PubSub implementation is intended for demo purposes. It only works if you have a single instance of your server and doesn't scale beyond a couple of connections. For production usage you'll want to use one of the PubSub implementations backed by an external store. (e.g. Redis)

Here is the [list](https://github.com/apollographql/graphql-subscriptions#pubsub-implementations) of alternatives. Question is, what should we use? I suppose, we don't want to bring Redis to the setup now? We may try to use [graphql-postgres-subscriptions](https://github.com/GraphQLCollege/graphql-postgres-subscriptions).

**Comment by nebolsin** [comment]
Let's use PG-based pubsub for now, we even [used to have one](https://github.com/astroband/astrograph/commit/3daab5e6dae22e13f5ea14a92ca2d8247f42236b#diff-97651bbb24c7d7b4cd79852e80437882) here :)

I think I've got some problems with 
[graphql-postgres-subscriptions](https://github.com/GraphQLCollege/graphql-postgres-subscriptions) and in the end I decided to go with [@udia/graphql-postgres-subscriptions](https://github.com/udia-software/graphql-postgres-subscriptions), although I don't remember the exact reasoning behind that decision.

**Comment by charlie-wasp** [comment]
> I don't remember the exact reasoning behind that decision
