### ISSUE TITLE
Question about query transaction

### ISSUE THREAD

**Issue by Ebioro** [astroband/astrograph#169]
Hi Guys,

Just found out your project and I can say that it rocks! I do have a question. I would like to query all the transactions associated to a specific account. I tried to query the following https://screencast.com/t/OWC9e8J93zpg. But of course I am doing something wrong

**Comment by charlie-wasp** [comment]
Hi @Ebioro!

We're glad you gave Astrograph a try!

Speaking of this error: you should provide paging params like this:

```
{
  account(id: "GB6NVEN5HSUBKMYCE5ZOWSK5K23TBWRUQLZY3KNMXUZ3AQ2ESC4MY4AQ") {
    id
    sequenceNumber
    ...
    transactions(first: 5) {
      nodes {
        id
      }
    }
  }
}
```

We surely improve error messaging in the future

**Comment by Ebioro** [comment]
Hi thanks!! 

I tried in the your demo site and it works :-). Another question. Which version of stellar core do you support at the moment? I get an error when trying in my local test environment. I am running core version 11.1.0-931-324c1bd6. The error I am getting:

1. Weird error that shows horizon public network instead of testnet 
`"errors": [
    {
      "message": "404: Not Found",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "account",
        "transactions"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "url": "https://horizon.stellar.org/accounts/GBSICOVSX3FF6CUEMW4M6D6X4D5A7VHCMZVO3LFFCYGF2HK2264A4OU3/transactions?limit=5&order=asc",
          "status": 404,
          "statusText": "Not Found",
          "body": "{\n  \"type\": \"https://stellar.org/horizon-errors/not_found\",\n  \"title\": \"Resource Missing\",\n  \"status\": 404,\n  \"detail\": \"The resource at the url requested was not found.  This is usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided.\"\n}"
        },
        "exception": {
          "stacktrace": [
            "Error: 404: Not Found",`
2. Get the transaction object as null 

` "data": {
    "account": {
      "id": "GBSICOVSX3FF6CUEMW4M6D6X4D5A7VHCMZVO3LFFCYGF2HK2264A4OU3",
      "sequenceNumber": "2039267652009985",
      "transactions": null,
      "balances": [
        {
          "asset": {
            "native": true,
            "issuer": null,
            "code": "XLM"
          },
          "balance": "9999.9999900",
          "limit": "922337203685.4775807",
          "authorized": true
        }
      ],
      "signers": null
    }
  },
  "extensions": {}
}`

You can check the transactions for the specified account in the example [here](https://horizon-testnet.stellar.org/accounts/GBSICOVSX3FF6CUEMW4M6D6X4D5A7VHCMZVO3LFFCYGF2HK2264A4OU3/transactions)

**Comment by charlie-wasp** [comment]
@Ebioro sorry for the late reply!

If you use our demo site, it runs over pubnet only, and it is supposed to support v11 of the core

If you setup your own instance of Astrograph, you should provide `STELLAR_NETWORK=testnet` environment variable to use testnet
