### ISSUE TITLE
findPaymemtPaths returns paths that cannot be executed due to "op_too_few_offers".

### ISSUE THREAD

**Issue by marcinx** [astroband/astrograph#174]
```
{findPaymentPaths(
    sourceAccountID: "GASKYWPPQ2VSO6KNIPIRVXMSSDGZLYZQ67CDTLVXOXYDG26SPZ66EDCQ",
    destinationAsset: "USD-GDUKMGUGDZQK6YHYA5Z6AY2G4XDSZPSZ3SW5UN3ARVMO6QSRDWP5YLEX",
    destinationAmount: "10"
) {
sourceAsset {
id
}
destinationAsset {
id
}
sourceAmount
path {
id
}
}
}
```

returns:

```
      {
        "sourceAsset": {
          "id": "XRP-GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5"
        },
        "destinationAsset": {
          "id": "USD-GDUKMGUGDZQK6YHYA5Z6AY2G4XDSZPSZ3SW5UN3ARVMO6QSRDWP5YLEX"
        },
        "sourceAmount": "26.4728568",
        "path": [
          {
            "id": "USD-GDSRCV5VTM3U7Y3L6DFRP3PEGBNQMGOWSRTGSBWX6Z3H6C7JHRI4XFJP"
          },
          {
            "id": "MXRT-GD2YURFWC5LIRLM4CCVZZHCFV6WXO46VOSBBPTJG6MPQN6ANYZZOLQJL"
          },
          {
            "id": "native"
          }
        ]
      },
```

This differs from Horizon results and fails to execute with `op_too_few_offers`. Horizon finds a path with 29.x source amount which executes fine.

Please let me know if you have questions or if there is anything I can assist you with in testing.

PS: We are adding 1.5% padding to sendMax parameter to counter possible price fluctuations and the price doesn't change significantly from obtaining the path to submitting the pathPayment.

**Comment by charlie-wasp** [comment]
Hi @marcinx ! It took a while to track down this bug, but we recently shipped the fix, can you please try it again?

**Comment by marcinx** [comment]
@charlie-wasp @nebolsin Thanks so much! In my first tests it seems to be working well now. I will keep you posted if I notice anything odd.

**Comment by charlie-wasp** [comment]
@marcinx I'm glad to hear it! 🎉 I close this issue for now, feel free to reopen it in case of new problems or you can create a new one
