### ISSUE TITLE
Which branch to use for DGraph support

### ISSUE THREAD

**Issue by sriramcms** [astroband/astrograph#177]
Astrograph is very cool project. 

I got it running using postgres and docker-stellar-core and ran some queries.  Now I would like to use it to ingest ledgers into a dgraph server 

I have 3 branches which has this support 
1. chore/dgraph-live
2. dgraph
3. rns/dgraph

Which one should i use ?

The mastebranch does not seem to have a DGRAPH_URL mentioned in the document.

Any help would be appreciated.

**Comment by sriramcms** [comment]
I was able to get rnd/dgraph running.  I also see some messages on the console like below.  So im guessing it is trying to sync the schema in dgraph -- 
set this in the .env file - DGRAPH_URL=localhost:9080

But when i try to open the dgraph console http://10.152.121.107:8000/?latest -  schema is empty and even the queries error out -- is there anything  I need to do to initialize  dgraph ?


otal: 151ms. Breakdown: [{sync 151ms} {disk 0s} {proposals 0s} {advance 0s}] Num entries: 1. MustSync: true
server_1  | I0728 20:25:39.448747       1 server.go:273] Received ALTER op: schema:"\n  \n  order: int @index(int) .\n  key: string @index(hash) .\n  kind.setOption: string .\n  kind.payment: string .\n  kind.pathPayment: string .\n  kind.manageOffer: string .\n  kind.manageDatum: string .\n  kind.createAccount: string .\n  kind.changeTrust: string .\n  kind.allowTrust: string .\n\n  \n  ledger.id: int @index(int) .\n  ledger.prev: uid @reverse .\n  version: int .\n  base_fee: int .\n  base_reserve: int .\n  max_tx_set_size: int .\n  close_time: datetime @index(hour) .\n  _ingested: bool .\n\n  \n  account.id: string @index(exact) .\n  account.created_by: uid @reverse .\n  account.merged_into: uid @reverse .\n

**Comment by charlie-wasp** [comment]
Hi @sriramcms! Thank you for trying out Astrograph!

Yes, you picked the right branch for DGraph support. However, we ditched DGraph, and now we're working on using ElasticSearch as storage. We built the separate tool for ledgers ingesting, check out [Astrologer](https://github.com/astroband/astrologer)

Speaking of the error you're struggling with, I guess, it's related to the DGraph version. DGraph team [wanted](https://github.com/dgraph-io/dgraph/issues/3116#issuecomment-471602675) to introduce `[uid]` schema type in 1.1 release, but it's still not there. We used the master branch of DGraph during development, so you can do so too

**Comment by sriramcms** [comment]
Thanks.
