### ISSUE TITLE
Private network

### ISSUE THREAD

**Issue by JFGHT** [astroband/astrograph#178]
Is it possible to connect to a Private Stellar network instead of the main net / oficial test net?

**Comment by charlie-wasp** [comment]
Hello! I’m afraid no, private networks are not supported at the moment. However, I believe it’s easy to add, I will look into it

**Comment by charlie-wasp** [comment]
@JFGHT I just pushed the code for using any network passphrase and updated the README on that part. You can check it out

**Comment by JFGHT** [comment]
@charlie-wasp thanks for the fast answer.

Maybe I'm wrong but doesn't this need a change as well?

https://github.com/astroband/astrograph/blob/9cda54c203bf3031f2a73de928c68c8ba38242ee/src/datasource/horizon/base.ts

Horizon could be in a private server :)

**Comment by charlie-wasp** [comment]
@JFGHT ah, yes, definitely :) Thank you! I pushed the fix for this too, now Astrograph supports `HORIZON_ENDPOINT` environment variable

**Comment by JFGHT** [comment]
Looks done!
